# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    campaignchain.operation.gotowebinar.add:
        bundle_name: "campaignchain/operation-gotowebinar"
        module_identifier: "campaignchain-gotowebinar"
        form_type: "CampaignChain\\Operation\\GoToWebinarBundle\\Form\\Type\\IncludeWebinarOperationType"

services:
    campaignchain.job.report.gotowebinar:
        class: CampaignChain\Operation\GoToWebinarBundle\Job\Report
        arguments: [ @doctrine.orm.entity_manager, @service_container ]
    campaignchain.operation.gotowebinar.webinar:
        class: CampaignChain\Operation\GoToWebinarBundle\EntityService\Webinar
        arguments: [ @doctrine.orm.entity_manager ]